entity:
  not-spawn: []
  explodeMone: "none" #none, onlyEntity, cancelled
autoclear:
  turn-on: true
  tick: 6000
  levels: [] #If blank, it is set as all Levels
  entities: ["Projectile", "ItemEntity"]